import { jsPDF } from "jspdf";

export function generateReport(result, diseaseInfo) {

    const doc = new jsPDF();

    const confidence = Math.round(result.confidence);

    const pageWidth = doc.internal.pageSize.getWidth();

    // ==========================
    // HEADER
    // ==========================

    doc.setFillColor(22, 101, 52);
    doc.rect(0, 0, pageWidth, 28, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.text("KrishiDrishti AI", 20, 18);

    doc.setFontSize(12);
    doc.text("AI Powered Plant Disease Diagnosis Report", 20, 25);

    // Reset text color

    doc.setTextColor(0, 0, 0);

    // ==========================
    // BASIC INFORMATION
    // ==========================

    let y = 45;

    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text("Diagnosis Summary", 20, y);

    y += 12;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(13);

    doc.text(
        `Disease : ${result.class.replace(/_/g, " ")}`,
        20,
        y
    );

    y += 10;

    doc.text(
        `Confidence : ${confidence}%`,
        20,
        y
    );

    y += 10;

    doc.text(
        `Severity : ${diseaseInfo.severity}`,
        20,
        y
    );

    y += 15;

    doc.line(20, y, 190, y);

    y += 12;

    // ==========================
    // DESCRIPTION
    // ==========================

    doc.setFont("helvetica", "bold");
    doc.setTextColor(22, 101, 52);
    doc.text("Description", 20, y);

    y += 8;

    doc.setTextColor(0,0,0);

    doc.setFont("helvetica","normal");

    doc.text(

        diseaseInfo.description,

        20,

        y,

        { maxWidth:170 }

    );

    y += 25;

    // ==========================
    // CAUSES
    // ==========================

    doc.setFont("helvetica","bold");

    doc.setTextColor(22,101,52);

    doc.text("Possible Causes",20,y);

    y += 10;

    doc.setFont("helvetica","normal");

    doc.setTextColor(0,0,0);

    diseaseInfo.causes?.forEach(item=>{

        doc.text("• "+item,25,y);

        y += 8;

    });

    y += 8;

    // ==========================
    // TREATMENT
    // ==========================

    doc.setFont("helvetica","bold");

    doc.setTextColor(22,101,52);

    doc.text("Recommended Treatment",20,y);

    y += 10;

    doc.setFont("helvetica","normal");

    doc.setTextColor(0,0,0);

    diseaseInfo.treatment?.forEach(item=>{

        doc.text("• "+item,25,y);

        y += 8;

    });

    y += 8;

    // ==========================
    // PREVENTION
    // ==========================

    doc.setFont("helvetica","bold");

    doc.setTextColor(22,101,52);

    doc.text("Preventive Measures",20,y);

    y += 10;

    doc.setFont("helvetica","normal");

    doc.setTextColor(0,0,0);

    diseaseInfo.prevention.forEach(item=>{

        doc.text("• "+item,25,y);

        y += 8;

    });

    y += 8;

    // ==========================
    // EXPERT ADVICE
    // ==========================

    doc.setFont("helvetica","bold");

    doc.setTextColor(22,101,52);

    doc.text("Expert Advice",20,y);

    y += 10;

    doc.setFont("helvetica","normal");

    doc.setTextColor(0,0,0);

    doc.text(

        diseaseInfo.expertAdvice,

        20,

        y,

        { maxWidth:170 }

    );

    // ==========================
    // FOOTER
    // ==========================

    const today = new Date();

    doc.setDrawColor(180);

    doc.line(20,270,190,270);

    doc.setFontSize(10);

    doc.setTextColor(100);

    doc.text(

        `Generated on ${today.toLocaleString()}`,

        20,

        278

    );

    doc.text(

        "Generated by KrishiDrishti AI",

        190,

        278,

        {align:"right"}

    );

    doc.save("KrishiDrishti_AI_Report.pdf");

}